/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ChiTietHDSP_DAO;
import Controller.ChiTietHD_DAO;
import Controller.ChiTietSP_DAO;
import Controller.HoaDon_DAO;
import Controller.KhachHang_DAO;
import Controller.NhanVien_DAO;
import Controller.SanPham_DAO;
import Model.ChiTietHoaDon;
import Model.ChiTietHoaDonSanPham;
import Model.ChiTietSanPham;
import Model.HoaDon;
import Model.KhachHang;
import Model.NhanVien;
import Model.SanPham;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author AN515
 */
public class QLDonHang extends javax.swing.JFrame {

    KhachHang_DAO daoKH = new KhachHang_DAO();
    HoaDon_DAO daoHD = new HoaDon_DAO();
    ChiTietHD_DAO daoCTHD = new ChiTietHD_DAO();
    ChiTietSP_DAO daoCTSP = new ChiTietSP_DAO();
    ChiTietHDSP_DAO daoCTHDSP = new ChiTietHDSP_DAO();
    NhanVien_DAO daoNV = new NhanVien_DAO();
    SanPham_DAO daoSP = new SanPham_DAO();
    private List<HoaDon> hoaDons;
    private List<SanPham> sanPhams;
    private List<ChiTietSanPham> ctsps;
    private DefaultTableModel modelHD;
    private DefaultTableModel modelSP;
    private DefaultTableModel modelCTSP;
    private DefaultComboBoxModel cbxModel;
    SimpleDateFormat formatDate = new SimpleDateFormat("dd/MM/yyyy");
    int selectedIndexRow;

    /**
     * Creates new form QLHoaDon
     */
    public QLDonHang() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelHD = (DefaultTableModel) tableHD.getModel();
        modelSP = (DefaultTableModel) tableSP.getModel();
        modelCTSP = (DefaultTableModel) tableCTSP.getModel();
        FillDataToTableSP();
        disableForm();
        getCbxLoaiKH();
        getCbxNhanVien();
        getToday();
        FillDataToTableHD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbxMaKH = new javax.swing.JComboBox<>();
        txtNgayDat = new javax.swing.JLabel();
        cbxNV = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        txtMaSP = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JLabel();
        txtGia = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnThemHD = new javax.swing.JButton();
        btnThemSP = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnXoaSP = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSP = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCTSP = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableHD = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnInHD = new javax.swing.JButton();
        txtMaHD = new javax.swing.JLabel();
        txtNgayDatHD = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JLabel();
        btnLuuCTHD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ ĐƠN HÀNG");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Mã khách hàng:");

        jLabel4.setText("Nhân viên:");

        jLabel10.setText("Ngày đặt (dd/MM/yyyy):");

        cbxMaKH.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbxMaKHPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbxMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMaKHActionPerformed(evt);
            }
        });

        txtNgayDat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtNgayDat.setForeground(new java.awt.Color(0, 0, 204));
        txtNgayDat.setText("Ngày đặt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxMaKH, 0, 150, Short.MAX_VALUE)
                            .addComponent(cbxNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(64, 64, 64)
                        .addComponent(jLabel10)
                        .addGap(26, 26, 26)
                        .addComponent(txtNgayDat, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cbxMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(txtNgayDat)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Mã sản phẩm:");

        jLabel8.setText("Tên sản phẩm:");

        jLabel9.setText("Số lượng:");

        jLabel5.setText("Giá bán:");

        txtMaSP.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtMaSP.setForeground(new java.awt.Color(0, 0, 204));
        txtMaSP.setText("Mã sản phẩm");

        txtTenSP.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtTenSP.setForeground(new java.awt.Color(0, 0, 204));
        txtTenSP.setText("Tên sản phẩm");

        txtGia.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtGia.setForeground(new java.awt.Color(0, 0, 204));
        txtGia.setText("Giá bán");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMaSP)
                    .addComponent(jLabel9)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGia)
                    .addComponent(jLabel8)
                    .addComponent(txtTenSP))
                .addGap(32, 32, 32))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnThemHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-24.png"))); // NOI18N
        btnThemHD.setText("Thêm hoá đơn");
        btnThemHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHDActionPerformed(evt);
            }
        });

        btnThemSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buy-24.png"))); // NOI18N
        btnThemSP.setText("Thêm sản phẩm");
        btnThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPActionPerformed(evt);
            }
        });

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-24.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save-as-24.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoaSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/return-24.png"))); // NOI18N
        btnXoaSP.setText("Xoá sản phẩm");
        btnXoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSPActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit-24.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnTimKiem)
                .addGap(82, 82, 82)
                .addComponent(btnThemHD, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnThemSP)
                .addGap(95, 95, 95)
                .addComponent(btnXoaSP)
                .addGap(84, 84, 84)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(btnThoat)
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem)
                    .addComponent(btnThemHD)
                    .addComponent(btnThemSP)
                    .addComponent(btnXoaSP)
                    .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThoat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Loại ", "Kích cỡ", "Màu sắc", "Số lượng", "Giá"
            }
        ));
        tableSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSP);
        if (tableSP.getColumnModel().getColumnCount() > 0) {
            tableSP.getColumnModel().getColumn(0).setMinWidth(10);
            tableSP.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Bảng danh sách sản phẩm");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("Chi tiết sản phẩm");

        tableCTSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Tổng giá"
            }
        ));
        jScrollPane2.setViewportView(tableCTSP);
        if (tableCTSP.getColumnModel().getColumnCount() > 0) {
            tableCTSP.getColumnModel().getColumn(0).setMinWidth(10);
            tableCTSP.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        tableHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã hoá đơn", "Ngày đặt", "Thành tiền"
            }
        ));
        tableHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHDMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableHD);
        if (tableHD.getColumnModel().getColumnCount() > 0) {
            tableHD.getColumnModel().getColumn(0).setMinWidth(10);
            tableHD.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jLabel13.setText("Mã hoá đơn:");

        jLabel14.setText("Ngày đặt:");

        jLabel15.setText("Thành tiền:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setText("Bảng danh sách hoá đơn");

        btnInHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/printer-24.png"))); // NOI18N
        btnInHD.setText("In hoá đơn");
        btnInHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInHDActionPerformed(evt);
            }
        });

        txtMaHD.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtMaHD.setForeground(new java.awt.Color(255, 0, 51));
        txtMaHD.setText("Mã hoá đơn");

        txtNgayDatHD.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtNgayDatHD.setForeground(new java.awt.Color(255, 0, 51));
        txtNgayDatHD.setText("Ngày đặt");

        txtThanhTien.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtThanhTien.setForeground(new java.awt.Color(255, 0, 51));
        txtThanhTien.setText("Thành tiền");

        btnLuuCTHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save-as-24.png"))); // NOI18N
        btnLuuCTHD.setText("Lưu hoá đơn");
        btnLuuCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuCTHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(615, 615, 615)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(69, 69, 69)
                                                .addComponent(jLabel14))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnLuuCTHD)
                                                .addGap(75, 75, 75)
                                                .addComponent(btnInHD)))
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNgayDatHD, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 5, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(txtMaHD)
                            .addComponent(txtNgayDatHD)
                            .addComponent(txtThanhTien)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLuuCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHDActionPerformed
        // TODO add your handling code here:
        txtMaSP.setText("Mã sản phẩm");
        txtTenSP.setText("Tên sản phẩm");
        txtSoLuong.setText("");
        txtGia.setText("Giá bán");
        enableForm();
        clearTable();
        showResult();
    }//GEN-LAST:event_btnThemHDActionPerformed

    private void cbxMaKHPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbxMaKHPopupMenuWillBecomeInvisible
        // TODO add your handling code here:        
    }//GEN-LAST:event_cbxMaKHPopupMenuWillBecomeInvisible

    private void tableSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSPMouseClicked
        // TODO add your handling code here:
        selectedIndexRow = tableSP.getSelectedRow();
        txtMaSP.setText(modelSP.getValueAt(selectedIndexRow, 1).toString());
        txtTenSP.setText(modelSP.getValueAt(selectedIndexRow, 2).toString());
        txtGia.setText(modelSP.getValueAt(selectedIndexRow, 7).toString());
    }//GEN-LAST:event_tableSPMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String name = txtTimKiem.getText();
        if (name.length() == 0) {
            FillDataToTableSP();
        } else if (name.length() > 0) {
            sanPhams = new SanPham_DAO().findByName(name);
            modelSP.setRowCount(0);
            for (SanPham s : sanPhams) {
                modelSP.addRow(new Object[]{
                    tableSP.getRowCount() + 1, s.getMaSP(), s.getTenSP(), s.getLoaiSP(), s.getKichCo(), s.getMauSac(), s.getSoluong(), s.getGiaBan()
                });
            }
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPActionPerformed
        // TODO add your handling code here:
        try {
            selectedIndexRow = tableCTSP.getSelectedRow();
            if (validateForm() == true) {
                String maSP = txtMaSP.getText(), tenSP = txtTenSP.getText();
                int sl = 0, gia = 0;
                sl = Integer.parseInt(txtSoLuong.getText());
                gia = Integer.parseInt(txtGia.getText());
                int tongGia = gia * sl;
                ChiTietSanPham c = new ChiTietSanPham(maSP, tenSP, sl, tongGia);
                c.setMaSP(maSP);
                c.setTenSP(tenSP);
                c.setSoLuong(sl);
                c.setTongGia(tongGia);
                new ChiTietSP_DAO().insert(c);
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
                showResult();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnThemSPActionPerformed

    private void btnXoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSPActionPerformed
        // TODO add your handling code here:
        selectedIndexRow = tableCTSP.getSelectedRow();
        ChiTietSanPham c = ctsps.get(selectedIndexRow);
        if (selectedIndexRow >= 0) {
            int reply = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xoá?");
            if (reply == JOptionPane.YES_OPTION) {
                new ChiTietSP_DAO().delete(c.getId());
                JOptionPane.showMessageDialog(this, "Đã xoá sản phẩm!");
                showResult();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không có sản phẩm để xoá!\nVui lòng chọn sản phẩm hoặc thêm sản phẩm!");
        }
    }//GEN-LAST:event_btnXoaSPActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        try {
            int reply = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn lưu không?");
            if (reply == JOptionPane.YES_OPTION) {
                selectedIndexRow = tableHD.getSelectedRow();
                int tongTien = 0;
                KhachHang maKH = daoKH.getByIDCus(cbxMaKH.getSelectedItem().toString());
                NhanVien maNV = daoNV.getIDNhanVienBH(cbxNV.getSelectedItem().toString());
                for (int i = 0; i < tableCTSP.getRowCount(); i++) {
                    tongTien += Integer.parseInt(tableCTSP.getValueAt(i, 4).toString());
                }
                HoaDon s = new HoaDon();
                s.setKhachHang(maKH);
                s.setNhanVien(maNV);
                s.setNgayDat(formatDate.parse(txtNgayDat.getText()));
                s.setThanhTien(tongTien);
                new HoaDon_DAO().insert(s);
                FillDataToTableHD();
                disableForm();
                btnLuuCTHD.setEnabled(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        String message = "Bạn có chắc muốn thoát?";
        String title = "Thoát";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            //System.exit(0);
            this.dispose();
        } else {
            return;
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnLuuCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuCTHDActionPerformed
        // TODO add your handling code here:
        try {
            int tongSL = 0;
            ChiTietHoaDon c = new ChiTietHoaDon();
            HoaDon idHD = daoHD.getByID(Integer.parseInt(txtMaHD.getText()));
            c.setHoaDon(idHD);
            int idCTSP = 0;
            for (int i = 0; i < tableCTSP.getRowCount(); i++) {
                idCTSP = (int) tableCTSP.getValueAt(i, 0);
            }
            c.setIdSanPham(idCTSP);
            for (int i = 0; i < tableCTSP.getRowCount(); i++) {
                tongSL += Integer.parseInt(tableCTSP.getValueAt(i, 3).toString());
            }
            c.setSoLuong(tongSL);
            new ChiTietHD_DAO().insert(c);
            JOptionPane.showMessageDialog(this, "Lưu hoá đơn thành công!");
            btnInHD.setEnabled(true);
            btnLuuCTHD.setEnabled(false);

            ChiTietHoaDonSanPham ct = new ChiTietHoaDonSanPham();
            ct.setIdHD(Integer.parseInt(txtMaHD.getText()));
            ct.setIdCTSP(idCTSP);
            ct.setThanhTien(Integer.parseInt(txtThanhTien.getText()));
            new ChiTietHDSP_DAO().insert(ct);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLuuCTHDActionPerformed

    private void cbxMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMaKHActionPerformed

    private void tableHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHDMouseClicked
        // TODO add your handling code here:
        selectedIndexRow = tableHD.getSelectedRow();
        txtMaHD.setText(modelHD.getValueAt(selectedIndexRow, 1).toString());
        txtNgayDatHD.setText(modelHD.getValueAt(selectedIndexRow, 2).toString());
        txtThanhTien.setText(modelHD.getValueAt(selectedIndexRow, 3).toString());
    }//GEN-LAST:event_tableHDMouseClicked

    private void btnInHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInHDActionPerformed
        // TODO add your handling code here:       
        String jdbc_driver = "com.mysql.cj.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/store_system_managerment";
        String user = "root";
        String password = "";
        File reportFile = new File(".");
        String dirr = "";
        try {
            Class.forName(jdbc_driver);
            Connection conn = (Connection) DriverManager.getConnection(url, user, password);
            Statement st = conn.createStatement();
            String sql = "SELECT *\n"
                    + "FROM `product details` \n"
                    + "INNER JOIN `product invoice details` ON `product details`.`id` = `product invoice details`.`id product details`";
            dirr = reportFile.getCanonicalPath() + "/src/Report/";
            JasperDesign design = JRXmlLoader.load(dirr + "report_HD.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(design);
            ResultSet rs = st.executeQuery(sql);
            JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
            JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap(), rsDataSource);
            JasperViewer.viewReport(jp);
            btnInHD.setEnabled(false);
        } catch (ClassNotFoundException | SQLException | IOException | JRException ex) {
            JOptionPane.showMessageDialog(null, "\nKhong in duoc\n" + ex, "Loi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInHDActionPerformed

    private boolean validateForm() {
        if (txtMaSP.getText().equals("Mã sản phẩm")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn sản phẩm!");
            return false;
        }
        if (txtSoLuong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập số lượng!");
            return false;
        }
        try {
            Integer.parseInt(txtSoLuong.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số lượng nhập phải là số, không được chứa ký tự!");
            return false;
        }
        try {
            int tmp = Integer.parseInt(txtSoLuong.getText());
            if (tmp == 0) {
                JOptionPane.showMessageDialog(this, "Số lượng bạn nhập vào phải lớn hơn 0");
                return false;
            }
        } catch (Exception e) {
        }
        return true;
    }

    private void clearTable() {
        new ChiTietHDSP_DAO().truncate();
        new ChiTietSP_DAO().truncate();
    }

    private void getToday() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        txtNgayDat.setText(dtf.format(now));
    }

    private void enableForm() {
        cbxMaKH.setEnabled(true);
        cbxNV.setEnabled(true);
        txtSoLuong.setEnabled(true);
        btnThemSP.setEnabled(true);
        btnLuu.setEnabled(true);
        btnXoaSP.setEnabled(true);
    }

    private void disableForm() {
        cbxMaKH.setEnabled(false);
        cbxNV.setEnabled(false);
        txtSoLuong.setEnabled(false);
        btnThemSP.setEnabled(false);
        btnXoaSP.setEnabled(false);
        btnLuu.setEnabled(false);
        btnInHD.setEnabled(false);
        btnLuuCTHD.setEnabled(false);
    }

    private void FillDataToTableHD() {
        hoaDons = new HoaDon_DAO().getListHoaDon();
        modelHD.setRowCount(0);
        for (HoaDon s : hoaDons) {
            modelHD.addRow(new Object[]{
                tableHD.getRowCount() + 1, s.getId(), formatDate.format(s.getNgayDat()), s.getThanhTien()
            });
        }
    }

    private void FillDataToTableSP() {
        sanPhams = new SanPham_DAO().getListSanPham();
        modelSP.setRowCount(0);
        for (SanPham s : sanPhams) {
            modelSP.addRow(new Object[]{
                tableSP.getRowCount() + 1, s.getMaSP(), s.getTenSP(), s.getLoaiSP(), s.getKichCo(), s.getMauSac(), s.getSoluong(), s.getGiaBan()
            });
        }
    }

    private void getCbxNhanVien() {
        cbxModel = (DefaultComboBoxModel) cbxNV.getModel();
        for (NhanVien nv : daoNV.getListNhanVienBH()) {
            cbxModel.addElement(nv);
        }
    }

    private void getCbxLoaiKH() {
        cbxModel = (DefaultComboBoxModel) cbxMaKH.getModel();
//        khachHangs = khdao.getListKhachHang();
//        for(KhachHang khach : khachHangs){
//            cbxIDKH.addItem(khach.getMaKH());
//        }      
        for (KhachHang khach : daoKH.getListKhachHang()) {
            cbxModel.addElement(khach);
        }
    }

    private void showResult() {
        ctsps = new ChiTietSP_DAO().getListCTSP();
        modelCTSP.setRowCount(0);
        for (ChiTietSanPham c : ctsps) {
            modelCTSP.addRow(new Object[]{
                c.getId(), c.getMaSP(), c.getTenSP(), c.getSoLuong(), c.getTongGia()
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDonHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInHD;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnLuuCTHD;
    private javax.swing.JButton btnThemHD;
    private javax.swing.JButton btnThemSP;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoaSP;
    private javax.swing.JComboBox<String> cbxMaKH;
    private javax.swing.JComboBox<String> cbxNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableCTSP;
    private javax.swing.JTable tableHD;
    private javax.swing.JTable tableSP;
    private javax.swing.JLabel txtGia;
    private javax.swing.JLabel txtMaHD;
    private javax.swing.JLabel txtMaSP;
    private javax.swing.JLabel txtNgayDat;
    private javax.swing.JLabel txtNgayDatHD;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JLabel txtTenSP;
    private javax.swing.JLabel txtThanhTien;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
