/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ChiTietPN_DAO;
import Controller.NhaPP_DAO;
import Controller.NhanVien_DAO;
import Controller.PhieuNhap_DAO;
import Controller.SanPham_DAO;
import Model.ChiTietPhieuNhap;
import Model.NhaPhanPhoi;
import Model.NhanVien;
import Model.PhieuNhap;
import Model.SanPham;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AN515
 */
public class QLPhieuNhap extends javax.swing.JFrame {

    NhanVien_DAO daoNV = new NhanVien_DAO();
    NhaPP_DAO daoNPP = new NhaPP_DAO();
    SanPham_DAO daoSP = new SanPham_DAO();
    PhieuNhap_DAO daoPN = new PhieuNhap_DAO();
    ChiTietPN_DAO daoCTPN = new ChiTietPN_DAO();
    private List<ChiTietPhieuNhap> ctpns;
    private List<PhieuNhap> phieuNhaps;
    private List<NhaPhanPhoi> nhaPhanPhois;
    private List<SanPham> sanPhams;
    private DefaultComboBoxModel cbxModel;
    private DefaultTableModel modelNPP;
    private DefaultTableModel modelSP;
    private DefaultTableModel modelPN;
    private DefaultTableModel modelCTPN;
    SimpleDateFormat formatDate = new SimpleDateFormat("dd/MM/yyyy");

    int selectedIndexRow;

    /**
     * Creates new form QLPhieuNhap
     */
    public QLPhieuNhap() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelNPP = (DefaultTableModel) tableNPP.getModel();
        modelSP = (DefaultTableModel) tableSP.getModel();
        modelPN = (DefaultTableModel) tablePN.getModel();
        modelCTPN = (DefaultTableModel) tableCTPN.getModel();
        getCbxNhanVien();
        getToday();
        FillDataToTableNPP();
        FillDataToTableSP();
        FillDataToTablePN();
        FillDataToTableCTPN();
        disableForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNPP = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSP = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxMaNV = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtMaNPP = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNgay = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIDNPP = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtMaSP = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtLoaiSP = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIDSP = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnLuuPN = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnThemPN = new javax.swing.JButton();
        btnXoaPN = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCTPN = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablePN = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtMaPN = new javax.swing.JLabel();
        btnLuuCTPN = new javax.swing.JButton();
        btnInPN = new javax.swing.JButton();
        txtTimKiemNPP = new javax.swing.JTextField();
        btnTimKiemNPP = new javax.swing.JButton();
        txtTimKiemSP = new javax.swing.JTextField();
        btnTimKiemSP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ PHIẾU NHẬP");

        tableNPP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mã", "Tên", "Địa Chỉ", "SĐT", "Email"
            }
        ));
        tableNPP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNPPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableNPP);
        if (tableNPP.getColumnModel().getColumnCount() > 0) {
            tableNPP.getColumnModel().getColumn(0).setMinWidth(10);
            tableNPP.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        tableSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mã", "Tên", "Loại", "Kích cỡ", "Màu", "Giá nhập"
            }
        ));
        tableSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableSP);
        if (tableSP.getColumnModel().getColumnCount() > 0) {
            tableSP.getColumnModel().getColumn(0).setMinWidth(10);
            tableSP.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Mã nhân viên:");

        jLabel3.setText("Mã nhà phân phối:");

        txtMaNPP.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtMaNPP.setForeground(new java.awt.Color(0, 0, 204));
        txtMaNPP.setText("Mã nhà phân phối");

        jLabel8.setText("Ngày:");

        txtNgay.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtNgay.setForeground(new java.awt.Color(0, 0, 204));
        txtNgay.setText("Ngày");

        jLabel9.setText("ID nhà phân phối:");

        txtIDNPP.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtIDNPP.setForeground(new java.awt.Color(0, 0, 204));
        txtIDNPP.setText("ID nhà phân phối");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIDNPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbxMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNPP, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtIDNPP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaNPP))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNgay))
                .addGap(23, 23, 23))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setFocusCycleRoot(true);

        txtMaSP.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtMaSP.setForeground(new java.awt.Color(0, 0, 204));
        txtMaSP.setText("Mã sản phẩm");

        jLabel12.setText("Loại sản phẩm:");

        jLabel13.setText("Giá nhập:");

        txtLoaiSP.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtLoaiSP.setForeground(new java.awt.Color(0, 0, 204));
        txtLoaiSP.setText("Loại sản phẩm");

        jLabel7.setText("Số lượng:");

        txtGiaNhap.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtGiaNhap.setForeground(new java.awt.Color(0, 0, 204));
        txtGiaNhap.setText("Giá nhập");

        jLabel19.setText("ID sản phẩm:");

        jLabel5.setText("Mã sản phẩm:");

        txtIDSP.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtIDSP.setForeground(new java.awt.Color(0, 0, 204));
        txtIDSP.setText("ID sản phẩm");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(jLabel19)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(33, 33, 33)))
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLoaiSP)
                    .addComponent(txtMaSP)
                    .addComponent(txtGiaNhap)
                    .addComponent(txtIDSP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtIDSP))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaSP))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtLoaiSP))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtGiaNhap))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLuuPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save-as-24.png"))); // NOI18N
        btnLuuPN.setText("Lưu phiếu nhập");
        btnLuuPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuPNActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit-24.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnThemPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-24.png"))); // NOI18N
        btnThemPN.setText("Thêm phiếu nhập");
        btnThemPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPNActionPerformed(evt);
            }
        });

        btnXoaPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete-24.png"))); // NOI18N
        btnXoaPN.setText("Xoá phiếu nhập");
        btnXoaPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPNActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(204, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("Lưu ý: Khi xoá phiếu nhập sẽ ảnh hưởng trực\ntiếp đến chi tiết phiếu nhập và đồng thời xảy\nra lỗi ngoài ý muốn!");
        jScrollPane5.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnXoaPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLuuPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemPN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuuPN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("Bảng danh sách nhà phân phối");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setText("Bảng danh sách sản phẩm");

        tableCTPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã phiếu nhập", "ID sản phẩm", "Số lượng"
            }
        ));
        jScrollPane3.setViewportView(tableCTPN);
        if (tableCTPN.getColumnModel().getColumnCount() > 0) {
            tableCTPN.getColumnModel().getColumn(0).setMinWidth(10);
            tableCTPN.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        tablePN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ID nhà phân phối", "Tổng tiền", "Ngày lập phiếu"
            }
        ));
        tablePN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePNMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablePN);
        if (tablePN.getColumnModel().getColumnCount() > 0) {
            tablePN.getColumnModel().getColumn(0).setMinWidth(10);
            tablePN.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel21.setText("Bảng danh sách phiếu nhập");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel22.setText("Bảng danh sách chi tiết phiếu nhập");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setText("Mã phiếu nhập:");

        txtMaPN.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtMaPN.setForeground(new java.awt.Color(0, 0, 204));
        txtMaPN.setText("Mã phiếu nhập");

        btnLuuCTPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save-as-24.png"))); // NOI18N
        btnLuuCTPN.setText("Lưu CT phiếu nhập");
        btnLuuCTPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuCTPNActionPerformed(evt);
            }
        });

        btnInPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/printer-24.png"))); // NOI18N
        btnInPN.setText("In Phiếu nhập");
        btnInPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInPNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(txtMaPN)
                .addGap(48, 48, 48)
                .addComponent(btnLuuCTPN)
                .addGap(39, 39, 39)
                .addComponent(btnInPN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLuuCTPN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(txtMaPN))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnInPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnTimKiemNPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-24.png"))); // NOI18N
        btnTimKiemNPP.setText("Tìm Kiếm");
        btnTimKiemNPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemNPPActionPerformed(evt);
            }
        });

        btnTimKiemSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-24.png"))); // NOI18N
        btnTimKiemSP.setText("Tìm Kiếm");
        btnTimKiemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(603, 603, 603))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                            .addComponent(jScrollPane4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTimKiemNPP, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTimKiemNPP))
                                    .addComponent(jLabel21))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                                .addComponent(jScrollPane3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTimKiemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTimKiemSP))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtTimKiemSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnTimKiemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtTimKiemNPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnTimKiemNPP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemNPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemNPPActionPerformed
        // TODO add your handling code here:
        String name = txtTimKiemNPP.getText();
        if (name.length() == 0) {
            FillDataToTableNPP();
        } else if (name.length() > 0) {
            nhaPhanPhois = new NhaPP_DAO().findByName(name);
            modelNPP.setRowCount(0);
            for (NhaPhanPhoi s : nhaPhanPhois) {
                modelNPP.addRow(new Object[]{
                    s.getId(), s.getMaNPP(), s.getTenNPP(), s.getDiaChi(), s.getSdt(), s.getEmail()
                });
            }
        }
    }//GEN-LAST:event_btnTimKiemNPPActionPerformed

    private void btnTimKiemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemSPActionPerformed
        // TODO add your handling code here:
        String name = txtTimKiemSP.getText();
        if (name.length() == 0) {
            FillDataToTableSP();
        } else if (name.length() > 0) {
            sanPhams = new SanPham_DAO().findByName(name);
            modelSP.setRowCount(0);
            for (SanPham s : sanPhams) {
                modelSP.addRow(new Object[]{
                    s.getId(), s.getMaSP(), s.getTenSP(), s.getLoaiSP(), s.getKichCo(), s.getMauSac(), s.getGiaNhap()
                });
            }
        }
    }//GEN-LAST:event_btnTimKiemSPActionPerformed

    private void tableNPPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNPPMouseClicked
        // TODO add your handling code here:
        selectedIndexRow = tableNPP.getSelectedRow();
        txtIDNPP.setText(modelNPP.getValueAt(selectedIndexRow, 0).toString());
        txtMaNPP.setText(modelNPP.getValueAt(selectedIndexRow, 1).toString());
    }//GEN-LAST:event_tableNPPMouseClicked

    private void tableSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSPMouseClicked
        // TODO add your handling code here:
        selectedIndexRow = tableSP.getSelectedRow();
        txtIDSP.setText(modelSP.getValueAt(selectedIndexRow, 0).toString());
        txtMaSP.setText(modelSP.getValueAt(selectedIndexRow, 1).toString());
        txtLoaiSP.setText(modelSP.getValueAt(selectedIndexRow, 3).toString());
        txtGiaNhap.setText(modelSP.getValueAt(selectedIndexRow, 6).toString());
    }//GEN-LAST:event_tableSPMouseClicked

    private void tablePNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePNMouseClicked
        // TODO add your handling code here:
        selectedIndexRow = tablePN.getSelectedRow();
        txtMaPN.setText(modelPN.getValueAt(selectedIndexRow, 0).toString());
    }//GEN-LAST:event_tablePNMouseClicked

    private void btnLuuCTPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuCTPNActionPerformed
        // TODO add your handling code here:
        try {
            ChiTietPhieuNhap s = new ChiTietPhieuNhap();
            s.setPhieuNhap(Integer.parseInt(txtMaPN.getText()));
            s.setSanPham(Integer.parseInt(txtIDSP.getText()));
            s.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
            new ChiTietPN_DAO().insert(s);
            JOptionPane.showMessageDialog(this, "Lưu thành công!");
            FillDataToTableCTPN();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLuuCTPNActionPerformed

    private void btnThemPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPNActionPerformed
        // TODO add your handling code here:
        txtIDNPP.setText("ID nhà phân phối");
        txtMaNPP.setText("Mã nhà phân phối");
        txtIDSP.setText("ID sản phẩm");
        txtMaSP.setText("Mã sản phẩm");
        txtLoaiSP.setText("Loại sản phẩm");
        txtGiaNhap.setText("Giá nhập");
        txtSoLuong.setText("");
        enableForm();
    }//GEN-LAST:event_btnThemPNActionPerformed

    private void btnLuuPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuPNActionPerformed
        // TODO add your handling code here:
        try {
            if (validateForm() == true) {
                int tong = 0;
                int gia = Integer.parseInt(txtGiaNhap.getText());
                int sl = Integer.parseInt(txtSoLuong.getText());
                PhieuNhap s = new PhieuNhap();
                NhanVien maNV = daoNV.getIDNhanVienKH(cbxMaNV.getSelectedItem().toString());
                s.setNhanVien(maNV);
                s.setNhaPP(Integer.parseInt(txtIDNPP.getText()));
                s.setNgayLap(formatDate.parse(txtNgay.getText()));
                tong = gia * sl;
                s.setTongTien(tong);
                new PhieuNhap_DAO().insert(s);
                JOptionPane.showMessageDialog(this, "Lưu thành công!");
                FillDataToTablePN();
                disableForm();
                btnLuuCTPN.setEnabled(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLuuPNActionPerformed

    private void btnXoaPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPNActionPerformed
        // TODO add your handling code here:
        try {
            selectedIndexRow = tablePN.getSelectedRow();
            PhieuNhap c = phieuNhaps.get(selectedIndexRow);
            if (selectedIndexRow >= 0) {
                int reply = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xoá?");
                if (reply == JOptionPane.YES_OPTION) {
                    new PhieuNhap_DAO().delete(c.getId());
                    JOptionPane.showMessageDialog(this, "Đã xoá phiếu nhập!");
                    FillDataToTablePN();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không có phiếu nhập để xoá!\nVui lòng chọn phiếu nhập hoặc thêm phiếu nhập!");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnXoaPNActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        String message = "Bạn có chắc muốn thoát?";
        String title = "Thoát";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            //System.exit(0);
            this.dispose();
        } else {
            return;
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnInPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInPNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInPNActionPerformed

    private void enableForm() {
        cbxMaNV.setEnabled(true);
        txtSoLuong.setEnabled(true);
        btnLuuPN.setEnabled(true);
    }

    private void disableForm() {
        cbxMaNV.setEnabled(false);
        txtSoLuong.setEnabled(false);
        btnLuuCTPN.setEnabled(false);
        btnLuuPN.setEnabled(false);
    }

    private boolean validateForm() {
        if (txtSoLuong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập số lượng!");
            return false;
        }
        try {
            Integer.parseInt(txtSoLuong.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số lượng nhập phải là số, không được chứa ký tự!");
            return false;
        }
        try {
            int tmp = Integer.parseInt(txtSoLuong.getText());
            if (tmp == 0) {
                JOptionPane.showMessageDialog(this, "Số lượng bạn nhập vào phải lớn hơn 0");
                return false;
            }
        } catch (Exception e) {
        }
        return true;
    }

    private void getCbxNhanVien() {
        cbxModel = (DefaultComboBoxModel) cbxMaNV.getModel();
        for (NhanVien nv : daoNV.getListNVKhoHang()) {
            cbxModel.addElement(nv);
        }
    }

    private void getToday() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        txtNgay.setText(dtf.format(now));
    }

    private void FillDataToTableNPP() {
        nhaPhanPhois = new NhaPP_DAO().getListNhaPP();
        modelNPP.setRowCount(0);
        for (NhaPhanPhoi s : nhaPhanPhois) {
            modelNPP.addRow(new Object[]{
                s.getId(), s.getMaNPP(), s.getTenNPP(), s.getDiaChi(), s.getSdt(), s.getEmail()
            });
        }
    }

    private void FillDataToTableCTPN() {
        ctpns = new ChiTietPN_DAO().getListChiTietPN();
        modelCTPN.setRowCount(0);
        for (ChiTietPhieuNhap s : ctpns) {
            modelCTPN.addRow(new Object[]{
                tableCTPN.getRowCount() + 1, s.getPhieuNhap(), s.getSanPham(), s.getSoLuong()
            });
        }
    }

    private void FillDataToTablePN() {
        phieuNhaps = new PhieuNhap_DAO().getListPhieuNhap();
        modelPN.setRowCount(0);
        for (PhieuNhap s : phieuNhaps) {
            modelPN.addRow(new Object[]{
                s.getId(), s.getNhaPP(), s.getTongTien(), formatDate.format(s.getNgayLap())
            });
        }
    }

    private void FillDataToTableSP() {
        sanPhams = new SanPham_DAO().getListAllSanPham();
        modelSP.setRowCount(0);
        for (SanPham s : sanPhams) {
            modelSP.addRow(new Object[]{
                s.getId(), s.getMaSP(), s.getTenSP(), s.getLoaiSP(), s.getKichCo(), s.getMauSac(), s.getGiaNhap()
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLPhieuNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInPN;
    private javax.swing.JButton btnLuuCTPN;
    private javax.swing.JButton btnLuuPN;
    private javax.swing.JButton btnThemPN;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiemNPP;
    private javax.swing.JButton btnTimKiemSP;
    private javax.swing.JButton btnXoaPN;
    private javax.swing.JComboBox<String> cbxMaNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tableCTPN;
    private javax.swing.JTable tableNPP;
    private javax.swing.JTable tablePN;
    private javax.swing.JTable tableSP;
    private javax.swing.JLabel txtGiaNhap;
    private javax.swing.JLabel txtIDNPP;
    private javax.swing.JLabel txtIDSP;
    private javax.swing.JLabel txtLoaiSP;
    private javax.swing.JLabel txtMaNPP;
    private javax.swing.JLabel txtMaPN;
    private javax.swing.JLabel txtMaSP;
    private javax.swing.JLabel txtNgay;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTimKiemNPP;
    private javax.swing.JTextField txtTimKiemSP;
    // End of variables declaration//GEN-END:variables
}
