/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author AN515
 */
public class TCAdmin extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuAdmin
     */
    public TCAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    String userAcc;

    public TCAdmin(String username) {
        initComponents();
        userAcc = username;
        txtUsername.setText(userAcc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subTitle = new javax.swing.JLabel();
        titile = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        txtPic = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnKhachHang = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnHangSX1 = new javax.swing.JButton();
        btnNhaPP = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        btnChucVu = new javax.swing.JButton();
        btnTaiKhoan = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnLoaiSP = new javax.swing.JButton();
        btnLapDonHang = new javax.swing.JButton();
        btnLapPhieuNhap = new javax.swing.JButton();
        btnThongKeDT = new javax.swing.JButton();
        btnThongKeCP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        subTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        subTitle.setText("ADMINISTRATOR");

        titile.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titile.setText("HỆ THỐNG QUẢN LÝ CỬA HÀNG QUẦN ÁO ");

        txtUsername.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        txtUsername.setText("username");

        txtPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/administrator-48.png"))); // NOI18N

        btnKhachHang.setBackground(new java.awt.Color(204, 204, 204));
        btnKhachHang.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/conference-32.png"))); // NOI18N
        btnKhachHang.setText("KHÁCH HÀNG");
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btnNhanVien.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/conference-call-32.png"))); // NOI18N
        btnNhanVien.setText("NHÂN VIÊN");
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        btnHangSX1.setBackground(new java.awt.Color(204, 204, 204));
        btnHangSX1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnHangSX1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/factory-32.png"))); // NOI18N
        btnHangSX1.setText("HÃNG SẢN XUẤT");
        btnHangSX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHangSX1ActionPerformed(evt);
            }
        });

        btnNhaPP.setBackground(new java.awt.Color(204, 204, 204));
        btnNhaPP.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnNhaPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/organization-32.png"))); // NOI18N
        btnNhaPP.setText("NHÀ PHÂN PHỐI");
        btnNhaPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaPPActionPerformed(evt);
            }
        });

        btnDangXuat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout-32.png"))); // NOI18N
        btnDangXuat.setText("ĐĂNG XUẤT");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnChucVu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/conference-call-32.png"))); // NOI18N
        btnChucVu.setText("CHỨC VỤ");
        btnChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChucVuActionPerformed(evt);
            }
        });

        btnTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user-3-32.png"))); // NOI18N
        btnTaiKhoan.setText("TÀI KHOẢN");
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });

        btnSanPham.setBackground(new java.awt.Color(204, 204, 204));
        btnSanPham.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/polish-cloth-32.png"))); // NOI18N
        btnSanPham.setText("SẢN PHẨM");
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });

        btnLoaiSP.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLoaiSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/product-32.png"))); // NOI18N
        btnLoaiSP.setText("LOẠI SẢN PHẨM");
        btnLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiSPActionPerformed(evt);
            }
        });

        btnLapDonHang.setBackground(new java.awt.Color(204, 204, 204));
        btnLapDonHang.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLapDonHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/purchase-order-32.png"))); // NOI18N
        btnLapDonHang.setText("LẬP ĐƠN HÀNG");
        btnLapDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapDonHangActionPerformed(evt);
            }
        });

        btnLapPhieuNhap.setBackground(new java.awt.Color(204, 204, 204));
        btnLapPhieuNhap.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLapPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/purchase-order-32.png"))); // NOI18N
        btnLapPhieuNhap.setText("LẬP PHIẾU NHẬP KHO");
        btnLapPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapPhieuNhapActionPerformed(evt);
            }
        });

        btnThongKeDT.setBackground(new java.awt.Color(204, 204, 204));
        btnThongKeDT.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnThongKeDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill-32.png"))); // NOI18N
        btnThongKeDT.setText("THỐNG KÊ DOANH THU");
        btnThongKeDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeDTActionPerformed(evt);
            }
        });

        btnThongKeCP.setBackground(new java.awt.Color(204, 204, 204));
        btnThongKeCP.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnThongKeCP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill-32.png"))); // NOI18N
        btnThongKeCP.setText("THỐNG KÊ CHI PHÍ");
        btnThongKeCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeCPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHangSX1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNhaPP, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLoaiSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThongKeCP, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongKeDT, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLapPhieuNhap)
                    .addComponent(btnLapDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLapPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLapDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHangSX1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongKeDT, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhaPP, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongKeCP, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(subTitle)
                        .addGap(330, 330, 330))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtPic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername)
                        .addGap(55, 55, 55))))
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(titile)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(txtUsername))
                    .addComponent(txtPic, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(titile)
                .addGap(18, 18, 18)
                .addComponent(subTitle)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        // TODO add your handling code here:
        QLKhachHang k = new QLKhachHang();
        k.setVisible(true);
        k.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnLapDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapDonHangActionPerformed
        // TODO add your handling code here:
        QLDonHang d = new QLDonHang();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnLapDonHangActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Đăng xuất thành công!");
        DangNhap d = new DangNhap();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnNhaPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaPPActionPerformed
        // TODO add your handling code here:
        QLNhaPP d = new QLNhaPP();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnNhaPPActionPerformed

    private void btnHangSX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHangSX1ActionPerformed
        // TODO add your handling code here:
        QLHangSX d = new QLHangSX();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnHangSX1ActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        QLNhanVien d = new QLNhanVien();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        // TODO add your handling code here:
        QLSanPham d = new QLSanPham();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiSPActionPerformed
        // TODO add your handling code here:
        QLLoaiSP d = new QLLoaiSP();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnLoaiSPActionPerformed

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        // TODO add your handling code here:
        QLNguoiDung d = new QLNguoiDung();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void btnChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChucVuActionPerformed
        // TODO add your handling code here:
        QLChucVu d = new QLChucVu();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnChucVuActionPerformed

    private void btnLapPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapPhieuNhapActionPerformed
        // TODO add your handling code here:
        QLPhieuNhap d = new QLPhieuNhap();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnLapPhieuNhapActionPerformed

    private void btnThongKeDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeDTActionPerformed
        // TODO add your handling code here:
        ThongKeChiPhi d = new ThongKeChiPhi();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnThongKeDTActionPerformed

    private void btnThongKeCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeCPActionPerformed
        // TODO add your handling code here:
        ThongKeChiPhi d = new ThongKeChiPhi();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnThongKeCPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TCAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChucVu;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHangSX1;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnLapDonHang;
    private javax.swing.JButton btnLapPhieuNhap;
    private javax.swing.JButton btnLoaiSP;
    private javax.swing.JButton btnNhaPP;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnThongKeCP;
    private javax.swing.JButton btnThongKeDT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel subTitle;
    private javax.swing.JLabel titile;
    private javax.swing.JLabel txtPic;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables
}
