/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author AN515
 */
public class TCNhapKho extends javax.swing.JFrame {

    /**
     * Creates new form TCNhapKho
     */
    public TCNhapKho() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    String userAcc;
    
    public TCNhapKho(String username) {
        initComponents();
        userAcc = username;
        txtUsername.setText(userAcc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titile = new javax.swing.JLabel();
        subTitle = new javax.swing.JLabel();
        btnSanPham = new javax.swing.JButton();
        btnLapPhieuNhap = new javax.swing.JButton();
        txtPic = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        btnThongKeCP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titile.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titile.setText("HỆ THỐNG QUẢN LÝ CỬA HÀNG QUẦN ÁO ");

        subTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        subTitle.setText("NHÂN VIÊN KHO HÀNG");

        btnSanPham.setBackground(new java.awt.Color(204, 204, 204));
        btnSanPham.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/polish-cloth-32.png"))); // NOI18N
        btnSanPham.setText("SẢN PHẨM");
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });

        btnLapPhieuNhap.setBackground(new java.awt.Color(204, 204, 204));
        btnLapPhieuNhap.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLapPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/purchase-order-32.png"))); // NOI18N
        btnLapPhieuNhap.setText("LẬP PHIẾU NHẬP KHO");
        btnLapPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapPhieuNhapActionPerformed(evt);
            }
        });

        txtPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fireman-48.png"))); // NOI18N

        txtUsername.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        txtUsername.setText("username");

        btnDangXuat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout-32.png"))); // NOI18N
        btnDangXuat.setText("ĐĂNG XUẤT");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnThongKeCP.setBackground(new java.awt.Color(204, 204, 204));
        btnThongKeCP.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnThongKeCP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill-32.png"))); // NOI18N
        btnThongKeCP.setText("THỐNG KÊ CHI PHÍ");
        btnThongKeCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeCPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThongKeCP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLapPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(subTitle))
                            .addComponent(titile))))
                .addGap(0, 198, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(txtUsername))
                    .addComponent(txtPic, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(titile)
                .addGap(18, 18, 18)
                .addComponent(subTitle)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLapPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongKeCP, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        // TODO add your handling code here:
        QLSanPham k = new QLSanPham();
        k.setVisible(true);
        k.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnLapPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapPhieuNhapActionPerformed
        // TODO add your handling code here:
        QLPhieuNhap d = new QLPhieuNhap();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnLapPhieuNhapActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Đăng xuất thành công!");
        DangNhap d = new DangNhap();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnThongKeCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeCPActionPerformed
        // TODO add your handling code here:
        ThongKeChiPhi d = new ThongKeChiPhi();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnThongKeCPActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCNhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCNhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCNhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCNhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TCNhapKho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnLapPhieuNhap;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnThongKeCP;
    private javax.swing.JLabel subTitle;
    private javax.swing.JLabel titile;
    private javax.swing.JLabel txtPic;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables
}
